### ISSUE TITLE
adonis-mongorito request.auth.attempt returning model.query is not a function

### ISSUE THREAD

**Issue by mubbashar** [allanfreitas/adonis-mongorito#2]
Trying to use mongo package https://github.com/thetutlage/adonis-mongorito with adonis framework. On 
`const login = yield request.auth.attempt(email, password);`
Getting 

`model.query is not a function`

Here is My User model file 

```
'use strict'

//const Lucid = use('Lucid')
const MongoritoModel = use('MongoritoModel')


class User extends MongoritoModel {

}

module.exports = User

```

**Comment by allanfreitas** [comment]
Hi @mubbashar , I will check this tomorrow (05/oct/2016), and give you a feedback on this.
But probably you will have to implement a "Auth Serializer/Scheme" to adonis-auth work with mongorito.

**Comment by niallobrien** [comment]
Is there any update on this? Thanks in advance.

**Comment by allanfreitas** [comment]
@niallobrien Not yet :(
I'm a bit "timeless" to check this right now.
It's on my priority list.

But the tip is, to use it With Adonis-Auth, we will have to implement an "Auth Serializer/Scheme".
So the method `const login = yield request.auth.attempt(email, password);`
will work.

**Comment by manoel-freitas** [comment]
So... i create a serializer for mongo( it's basically a copy of Lucid) and i'm getting a issue here on how to use IOC.use(Model), and get the primary key of the model. do you know or tried anything like that ?

**Comment by oscarnevarezleal** [comment]
I´ve created a Auth Serializer/Scheme for this. Sending PR

https://github.com/oscarnevarezleal/adonis-mongorito

**Comment by allanfreitas** [comment]
@oscarnevarezleal Thanks,
I've just merged the PR.

@laedanthehuman 
@mubbashar @niallobrien
