### ISSUE TITLE
Implementing relation ship 

### ISSUE THREAD

**Issue by pishguy** [allanfreitas/adonis-mongorito#3]
can i make relation ship between collections easily?

**Comment by allanfreitas** [comment]
Sorry for the delay, I will check this on on thursday morning.

**Comment by Nefiron** [comment]
Any news on this one?

**Comment by pishguy** [comment]
@Nefiron  i dont think

**Comment by NicoG11** [comment]
Have you found a solution?
Have you tried the Query Population method ?
[Here from the Mongorito Docs](http://mongorito.com/guides/query-population/)

Maybe this is a workaround for your Problem

**Comment by allanfreitas** [comment]
@MahdiPishguy If you check the package code, it's only a simple integration to Mongorito package.
Then, things like relations or how I can query like something, the anwser probably will be on Mongorito Docs :)

@Nefiron @NicoG11
