### ISSUE TITLE
orderBy

### ISSUE THREAD

**Issue by themodernpk** [allanfreitas/adonis-mongorito#6]
Can you tell me the correct systax for orderBy? I am trying following:

```yield Post.orderBy('date_time', 'desc').findOne();```

**Comment by allanfreitas** [comment]
Sorry for the delay, I will check this on on thursday morning.

**Comment by Nefiron** [comment]
Following this. :)

**Comment by NicoG11** [comment]
> `yield Post.orderBy('date_time', 'desc').findOne();`

use 1 for ASC and -1 for DESC, and the sort function

This query would get the last Post that was created (field in db is created_at)
`yield Post.sort('created_at', -1).findOne()`

Example with where
```javascript
// get all Post from Type 1 order by created desc
yield Post.where('type', 1).sort('created_at', -1).find()
// or
// get all Post from Type 1 order by created asc
yield Post.where('type', 1).sort('created_at', 1).find()
```
Have a look at: [The Mongorito Guides](http://mongorito.com/guides/queries/)

**Comment by allanfreitas** [comment]
@webreinvent Sorry for the delay again.
I'm with short time to actively maintining this repo right now, but I've tested the @NicoG11 solution and It Works, and This package it's only a simple way to have Adonis Connected with the Mongorito Package :),

So, many things you can check ate the [Mongorito Docs](http://mongorito.com/guides/queries/) :)
